import Head from 'next/head'
import styles from '../styles/Home.module.css';
import { signIn, signOut, useSession} from 'next-auth/react'

export default function Home() {
  const {data:session, status:loading} = useSession();
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div>
        { !session && (
              <>
                  <p className={styles.notsignin}>Not signed in</p>
                  <button className={styles.button} onClick={() => signIn()}>Sign in</button>
              </>
            )
              
             }

         { session && (
          <>
                  <p>you are Sign in</p>
                    <button onClick={() => signOut()}>Sign out</button> 
          </>
         )
         }
           
        </div>
      </main>

      
    </div>
  )
}


// if (session) {
//   return (
//     <>
//       Signed in as ..... <br />
//       <button onClick={() => signOut()}>Sign out</button>
//     </>
//   )
// }
// return (
//   <>
//     Not signed in <br />
//     <button onClick={() => signIn()}>Sign in</button>
//   </>
// )
// }